import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F4F7F1",
  },
  content: {
    paddingHorizontal: 20,
    paddingBottom: 32,
    gap: 18,
  },
  heroCard: {
    marginTop: 12,
    backgroundColor: "#17351A",
    borderRadius: 28,
    padding: 22,
    shadowColor: "#17351A",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
  },
  heroTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  eyebrow: {
    color: "#B6D6B0",
    fontSize: 13,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  heroTitle: {
    marginTop: 8,
    color: "#F6F8F2",
    fontSize: 32,
    fontWeight: "700",
    maxWidth: 240,
    lineHeight: 38,
  },
  heroSubtitle: {
    marginTop: 14,
    color: "#D0E1CB",
    fontSize: 15,
    lineHeight: 22,
    maxWidth: 290,
  },
  plusButton: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: "#95CB68",
    alignItems: "center",
    justifyContent: "center",
  },
  plusButtonText: {
    color: "#17351A",
    fontSize: 30,
    fontWeight: "400",
    marginTop: -2,
  },
  statRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 20,
  },
  statCard: {
    flex: 1,
    backgroundColor: "#244A28",
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 12,
  },
  statValue: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "700",
  },
  statLabel: {
    color: "#B6D6B0",
    fontSize: 12,
    marginTop: 4,
  },
  sectionCard: {
    backgroundColor: "#FCFDF9",
    borderRadius: 26,
    padding: 18,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sectionTitle: {
    color: "#1F3120",
    fontSize: 22,
    fontWeight: "700",
  },
  sectionSubtitle: {
    color: "#7D8B77",
    fontSize: 13,
    marginTop: 4,
  },
  legend: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  legendText: {
    color: "#7D8B77",
    fontSize: 11,
  },
  legendSwatch: {
    width: 12,
    height: 12,
    borderRadius: 3,
  },
  calendarShell: {
    marginTop: 18,
    backgroundColor: "#F4F7F1",
    borderRadius: 22,
    padding: 14,
  },
  monthRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingLeft: 32,
    paddingRight: 6,
  },
  monthLabel: {
    color: "#91A08B",
    fontSize: 11,
    minWidth: 18,
  },
  calendarRow: {
    flexDirection: "row",
    marginTop: 10,
  },
  dayLabels: {
    justifyContent: "space-between",
    marginRight: 8,
  },
  dayLabelSlot: {
    height: 14,
    justifyContent: "center",
  },
  dayLabel: {
    width: 22,
    color: "#91A08B",
    fontSize: 10,
  },
  weekColumns: {
    flexDirection: "row",
    gap: 6,
  },
  weekColumn: {
    gap: 6,
  },
  dayCell: {
    width: 14,
    height: 14,
    borderRadius: 4,
  },
  taskCard: {
    backgroundColor: "#FCFDF9",
    borderRadius: 24,
    padding: 18,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  taskInfo: {
    flex: 1,
    paddingRight: 16,
  },
  taskTypeBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#E5EFDA",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginBottom: 10,
  },
  taskTypeText: {
    color: "#436535",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  taskTitle: {
    color: "#1F3120",
    fontSize: 18,
    fontWeight: "700",
  },
  taskMeta: {
    color: "#7D8B77",
    fontSize: 13,
    marginTop: 6,
  },
  taskActions: {
    alignItems: "center",
    gap: 10,
  },
  completeButton: {
    minWidth: 92,
    borderRadius: 14,
    backgroundColor: "#17351A",
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  completeButtonDone: {
    backgroundColor: "#DCE9D1",
  },
  completeButtonText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
  },
  completeButtonTextDone: {
    color: "#33502A",
  },
  ellipsisButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "#EFF4E7",
    alignItems: "center",
    justifyContent: "center",
  },
  ellipsisText: {
    color: "#33502A",
    fontSize: 18,
    fontWeight: "700",
    marginTop: -6,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(19, 31, 15, 0.35)",
    justifyContent: "flex-end",
    padding: 18,
  },
  modalCard: {
    backgroundColor: "#FCFDF9",
    borderRadius: 30,
    padding: 22,
    gap: 14,
  },
  modalTitle: {
    color: "#1F3120",
    fontSize: 24,
    fontWeight: "700",
  },
  modalSubtitle: {
    color: "#7D8B77",
    fontSize: 14,
    lineHeight: 20,
  },
  input: {
    backgroundColor: "#F2F6EC",
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: "#1F3120",
    fontSize: 15,
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 8,
  },
  secondaryAction: {
    flex: 1,
    borderRadius: 16,
    backgroundColor: "#ECF2E4",
    paddingVertical: 15,
    alignItems: "center",
  },
  secondaryActionText: {
    color: "#355229",
    fontSize: 15,
    fontWeight: "700",
  },
  primaryAction: {
    flex: 1,
    borderRadius: 16,
    backgroundColor: "#8FCE5A",
    paddingVertical: 15,
    alignItems: "center",
  },
  primaryActionText: {
    color: "#17351A",
    fontSize: 15,
    fontWeight: "700",
  },
});
