import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F4F7F1",
  },
  screen: {
    flex: 1,
  },
  stickyHeaderContainer: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 12,
    backgroundColor: "#F4F7F1",
    zIndex: 10,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 120,
    gap: 18,
  },
  contentBelowStickyHeader: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 120,
    gap: 18,
  },
  pageHeader: {
    gap: 8,
  },
  backButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: "#ECF2E4",
  },
  backButtonPressed: {
    opacity: 0.75,
  },
  backButtonText: {
    color: "#355229",
    fontSize: 20,
    fontWeight: "800",
    marginTop: -2,
  },
  backButtonLabel: {
    color: "#355229",
    fontSize: 13,
    fontWeight: "700",
    maxWidth: 220,
  },
  eyebrow: {
    color: "#7B8D72",
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  pageTitle: {
    color: "#1F3120",
    fontSize: 34,
    fontWeight: "700",
  },
  pageSubtitle: {
    color: "#7D8B77",
    fontSize: 15,
    lineHeight: 22,
    maxWidth: 320,
  },
  heroCard: {
    backgroundColor: "#17351A",
    borderRadius: 28,
    padding: 22,
    shadowColor: "#17351A",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
  },
  heroTitle: {
    color: "#F6F8F2",
    fontSize: 28,
    fontWeight: "700",
    lineHeight: 34,
  },
  heroSubtitle: {
    marginTop: 10,
    color: "#D0E1CB",
    fontSize: 15,
    lineHeight: 22,
  },
  statRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 20,
  },
  statCard: {
    flex: 1,
    flexBasis: 0,
    minWidth: 0,
    backgroundColor: "#244A28",
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 12,
  },
  statValue: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "700",
  },
  statLabel: {
    color: "#B6D6B0",
    fontSize: 12,
    marginTop: 4,
  },
  sectionCard: {
    backgroundColor: "#FCFDF9",
    borderRadius: 26,
    padding: 18,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  sectionHeaderStack: {
    marginTop: 15,
    gap: 2,
  },
  sectionTitle: {
    color: "#1F3120",
    fontSize: 22,
    fontWeight: "700",
  },
  sectionSubtitle: {
    color: "#7D8B77",
    fontSize: 13,
    marginTop: 4,
  },
  legend: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    justifyContent: "flex-end",
    marginTop: 12,
  },
  legendText: {
    color: "#7D8B77",
    fontSize: 11,
  },
  legendSwatch: {
    width: 12,
    height: 12,
    borderRadius: 3,
  },
  calendarShell: {
    marginTop: 18,
    backgroundColor: "#F4F7F1",
    borderRadius: 22,
    padding: 14,
  },
  monthRow: {
    flexDirection: "row",
    gap: 6,
    height: 14,
    marginBottom: 10,
  },
  monthLabelSlot: {
    width: 14,
    position: "relative",
  },
  monthLabelText: {
    position: "absolute",
    left: 0,
    top: -1,
    width: 40,
    color: "#91A08B",
    fontSize: 11,
  },
  monthSpacer: {
    height: 24,
  },
  calendarRow: {
    flexDirection: "row",
  },
  dayLabelsColumn: {
    marginRight: 8,
  },
  dayLabels: {
    flex: 1,
    justifyContent: "space-between",
  },
  dayLabelSlot: {
    height: 14,
    justifyContent: "center",
  },
  dayLabel: {
    width: 22,
    color: "#91A08B",
    fontSize: 10,
  },
  weekColumns: {
    flexDirection: "row",
    gap: 6,
  },
  weekColumn: {
    gap: 6,
  },
  dayCell: {
    width: 14,
    height: 14,
    borderRadius: 4,
  },
  dayCellEmpty: {
    width: 14,
    height: 14,
  },
  categorySection: {
    gap: 12,
  },
  categoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  categoryBadge: {
    backgroundColor: "#E5EFDA",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    alignSelf: "flex-start",
  },
  categoryBadgeText: {
    color: "#436535",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  categoryCount: {
    color: "#7D8B77",
    fontSize: 13,
    fontWeight: "600",
  },
  taskCard: {
    backgroundColor: "#FCFDF9",
    borderRadius: 24,
    padding: 18,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 14,
  },
  taskInfo: {
    flex: 1,
    paddingRight: 8,
  },
  taskTypeBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#E5EFDA",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginBottom: 10,
  },
  taskTypeText: {
    color: "#436535",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  taskTitle: {
    color: "#1F3120",
    fontSize: 18,
    fontWeight: "700",
  },
  taskHabitName: {
    color: "#4A6643",
    fontSize: 14,
    marginTop: 4,
    fontWeight: "600",
  },
  taskMeta: {
    color: "#7D8B77",
    fontSize: 13,
    marginTop: 6,
  },
  taskActions: {
    alignItems: "center",
    gap: 10,
  },
  completeButton: {
    minWidth: 92,
    borderRadius: 14,
    backgroundColor: "#17351A",
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  completeButtonDone: {
    backgroundColor: "#DCE9D1",
  },
  completeButtonText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
  },
  completeButtonTextDone: {
    color: "#33502A",
  },
  ellipsisButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "#EFF4E7",
    alignItems: "center",
    justifyContent: "center",
  },
  ellipsisText: {
    color: "#33502A",
    fontSize: 18,
    fontWeight: "700",
    marginTop: -6,
  },
  habitRow: {
    backgroundColor: "#FCFDF9",
    borderRadius: 22,
    padding: 18,
    gap: 8,
  },
  habitRowPressable: {
    opacity: 1,
  },
  habitRowPressed: {
    opacity: 0.75,
  },
  habitName: {
    color: "#1F3120",
    fontSize: 18,
    fontWeight: "700",
  },
  helperText: {
    color: "#7D8B77",
    fontSize: 13,
    lineHeight: 19,
  },
  emptyCard: {
    backgroundColor: "#FCFDF9",
    borderRadius: 24,
    padding: 20,
    gap: 8,
    alignItems: "flex-start",
  },
  emptyTitle: {
    color: "#1F3120",
    fontSize: 18,
    fontWeight: "700",
  },
  emptyText: {
    color: "#7D8B77",
    fontSize: 14,
    lineHeight: 21,
  },
  modalFullScreen: {
    flex: 1,
    backgroundColor: "#F4F7F1",
  },
  modalTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 10,
  },
  modalTopIconButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#FCFDF9",
    alignItems: "center",
    justifyContent: "center",
  },
  modalTopIconText: {
    color: "#1F3120",
    fontSize: 18,
    fontWeight: "800",
    marginTop: -2,
  },
  modalTopTitle: {
    flex: 1,
    textAlign: "center",
    color: "#1F3120",
    fontSize: 18,
    fontWeight: "800",
  },
  modalScrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 34,
    gap: 14,
  },
  modalLeadText: {
    color: "#7D8B77",
    fontSize: 15,
    lineHeight: 22,
    marginTop: 6,
    marginBottom: 4,
  },
  modalSectionCard: {
    backgroundColor: "#FCFDF9",
    borderRadius: 28,
    padding: 18,
    gap: 14,
  },
  habitNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  habitIconButton: {
    width: 54,
    height: 54,
    borderRadius: 18,
    backgroundColor: "#F2F6EC",
    alignItems: "center",
    justifyContent: "center",
  },
  habitIconText: {
    fontSize: 26,
  },
  habitNameInput: {
    flex: 1,
  },
  hiddenEmojiInput: {
    position: "absolute",
    width: 1,
    height: 1,
    opacity: 0,
    left: -100,
    top: -100,
  },
  emojiGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  emojiCell: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: "#F2F6EC",
    alignItems: "center",
    justifyContent: "center",
  },
  emojiCellSelected: {
    backgroundColor: "#17351A",
  },
  emojiCellText: {
    fontSize: 26,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(19, 31, 15, 0.35)",
    justifyContent: "flex-end",
    padding: 18,
  },
  modalCard: {
    backgroundColor: "#FCFDF9",
    borderRadius: 30,
    padding: 22,
    gap: 14,
    overflow: "visible",
  },
  modalCardExpanded: {
    paddingBottom: 30,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  modalHeaderText: {
    flex: 1,
  },
  modalTitle: {
    color: "#1F3120",
    fontSize: 24,
    fontWeight: "700",
  },
  modalSubtitle: {
    color: "#7D8B77",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 6,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: "#ECF2E4",
    alignItems: "center",
    justifyContent: "center",
  },
  closeButtonText: {
    color: "#355229",
    fontSize: 16,
    fontWeight: "700",
  },
  input: {
    backgroundColor: "#F2F6EC",
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: "#1F3120",
    fontSize: 15,
  },
  multilineInput: {
    minHeight: 94,
    textAlignVertical: "top",
  },
  optionGroup: {
    gap: 10,
  },
  fieldLabel: {
    color: "#4A6643",
    fontSize: 13,
    fontWeight: "700",
  },
  optionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  optionChip: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: "#ECF2E4",
  },
  optionChipActive: {
    backgroundColor: "#17351A",
  },
  optionChipText: {
    color: "#355229",
    fontSize: 13,
    fontWeight: "700",
  },
  optionChipTextActive: {
    color: "#F6F8F2",
  },
  dropdownField: {
    gap: 10,
  },
  colorPickerField: {
    gap: 10,
  },
  colorPickerRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  colorPickerHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  colorValueText: {
    flex: 1,
    color: "#1F3120",
    fontSize: 14,
    fontWeight: "700",
  },
  colorPickerButton: {
    borderRadius: 14,
    backgroundColor: "#ECF2E4",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  colorPickerButtonText: {
    color: "#355229",
    fontSize: 13,
    fontWeight: "700",
  },
  colorPickerPanel: {
    marginTop: 10,
    gap: 12,
    backgroundColor: "#eaece9",
    borderRadius: 8,
    padding: 12,
  },
  colorPickerModalCard: {
    maxHeight: "85%",
  },
  colorPickerModalHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  colorPickerPanelSquare: {
    height: 250,
    borderRadius: 8,
  },
  colorPickerSlider: {
    borderRadius: 50,
    overflow: "hidden",
    backgroundColor: "transparent",
  },
  colorPickerReadout: {
    textAlign: "left",
    color: "#5F7356",
    fontSize: 14,
    fontWeight: "600",
    marginTop: 6,
  },
  colorPickerThumbRing: {
    position: "absolute",
    left: 0,
    top: 0,
    borderWidth: 2,
    backgroundColor: "transparent",
  },
  colorPickerThumbFill: {
    position: "absolute",
  },
  colorSwatch: {
    width: 32,
    height: 32,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: "rgba(31, 49, 32, 0.12)",
  },
  colorSwatchSelected: {
    borderWidth: 5,
    borderColor: "#B3E561",
  },
  colorInputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  colorPreview: {
    width: 36,
    height: 36,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#DDE5D6",
    backgroundColor: "#FFFFFF",
  },
  colorInput: {
    flex: 1,
  },
  dropdownLayerTop: {
    zIndex: 3000,
  },
  dropdownValue: {
    backgroundColor: "#F2F6EC",
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  dropdownValueText: {
    color: "#1F3120",
    fontSize: 15,
  },
  dropdownOptions: {
    gap: 8,
  },
  dropdownOption: {
    backgroundColor: "#ECF2E4",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  dropdownOptionActive: {
    backgroundColor: "#17351A",
  },
  dropdownOptionText: {
    color: "#355229",
    fontSize: 14,
    fontWeight: "600",
  },
  dropdownOptionTextActive: {
    color: "#F6F8F2",
  },
  dropdownPicker: {
    borderWidth: 0,
    borderRadius: 16,
    backgroundColor: "#F2F6EC",
    minHeight: 54,
    paddingHorizontal: 4,
    paddingLeft:16,
  },
  dropdownPickerContainer: {
    borderWidth: 0,
    borderRadius: 16,
    backgroundColor: "#FCFDF9",
    marginTop: 8,
    shadowColor: "#17351A",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
  },
  dropdownPickerText: {
    color: "#1F3120",
    fontSize: 15,
  },
  dropdownPickerPlaceholder: {
    color: "#8A957A",
  },
  dropdownChevron: {
    color: "#355229",
    fontSize: 18,
    fontWeight: "700",
    marginRight: 8,
    paddingRight: 5,
  },
  addOptionRow: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  addCategoryPanel: {
    gap: 10,
    backgroundColor: "#F4F7F1",
    borderRadius: 18,
    padding: 12,
  },
  addCategoryHint: {
    color: "#5F7356",
    fontSize: 13,
    lineHeight: 18,
  },
  addOptionInput: {
    flex: 1,
  },
  addOptionButton: {
    borderRadius: 16,
    backgroundColor: "#17351A",
    paddingHorizontal: 16,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  addOptionButtonText: {
    color: "#F6F8F2",
    fontSize: 14,
    fontWeight: "700",
  },
  primaryActionFull: {
    borderRadius: 16,
    backgroundColor: "#8FCE5A",
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 6,
  },
  primaryActionSplit: {
    flex: 1,
    borderRadius: 16,
    backgroundColor: "#8FCE5A",
    paddingVertical: 16,
    alignItems: "center",
  },
  primaryActionText: {
    color: "#17351A",
    fontSize: 15,
    fontWeight: "700",
  },
  modalFooterRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 6,
  },
  secondaryAction: {
    flex: 1,
    borderRadius: 16,
    backgroundColor: "#ECF2E4",
    paddingVertical: 16,
    alignItems: "center",
  },
  secondaryActionText: {
    color: "#355229",
    fontSize: 15,
    fontWeight: "700",
  },
  fabWrapper: {
    position: "absolute",
    right: 24,
    bottom: 24,
    alignItems: "flex-end",
    gap: 10,
  },
  fabMenu: {
    gap: 10,
  },
  fabMenuItem: {
    backgroundColor: "#FCFDF9",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    minWidth: 132,
    shadowColor: "#17351A",
    shadowOpacity: 0.12,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
  },
  fabMenuLabel: {
    color: "#1F3120",
    fontSize: 14,
    fontWeight: "700",
  },
  fabButton: {
    width: 62,
    height: 62,
    borderRadius: 22,
    backgroundColor: "#8FCE5A",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#17351A",
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  fabButtonText: {
    color: "#17351A",
    fontSize: 30,
    fontWeight: "400",
    marginTop: -2,
  },
});
